<?php
/**
 *
 * @description Geo IP popup template
 *
 * @author Bina Commerce      <https://www.binacommerce.com>
 * @author C. M. de Picciotto <cmdepicciotto@binacommerce.com>
 *
 */
?>

<?php
/**
 *
 * @var \Bina\GeoIp\Block\Popup $block
 *
 */
?>

<?php
/**
 *
 * @note Check if feature is active
 *
 */
?>
<?php if ($block->isActive()): ?>
    <?php
    /**
     *
     * @note Add popup
     *
     */
    ?>
    <script type="text/x-magento-init">
    {
        "*": {
            "geoIpPopup": {
                "checkIpUrl": "<?= $block->getCheckIpUrl() ?>",
                "currentUrl": "<?= $block->getCurrentUrl() ?>"
            }
        }
    }
    </script>
<?php endif; ?>